import HomeFooter from "../feature-plugins/home/footer.js";
import HomeTips from "../feature-plugins/home/tips.js";
import SidebarContext from "../feature-plugins/sidebar/context.js";
import SidebarMcp from "../feature-plugins/sidebar/mcp.js";
import SidebarLsp from "../feature-plugins/sidebar/lsp.js";
import SidebarTodo from "../feature-plugins/sidebar/todo.js";
import SidebarFiles from "../feature-plugins/sidebar/files.js";
import SidebarFooter from "../feature-plugins/sidebar/footer.js";
import PluginManager from "../feature-plugins/system/plugins.js";
import SessionV2Debug from "../feature-plugins/system/session-v2.js";
import { Flag } from "core/flag/flag";
export const INTERNAL_TUI_PLUGINS = [HomeFooter, HomeTips, SidebarContext, SidebarMcp, SidebarLsp, SidebarTodo, SidebarFiles, SidebarFooter, PluginManager, ...(Flag.CLOSEDCODE_EXPERIMENTAL_EVENT_SYSTEM ? [SessionV2Debug] : [])];