#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const colors = await readFile(path.join(here, "colors.txt"), "utf8");
const variables = [];
for (const line of colors.split("\n")) {
  if (!line.trim()) continue;
  const [variable] = line.trim().split(":");
  const name = variable.trim().substring(2);
  variables.push(`--color-${name}: var(--${name});`);
}
const output = `
/* Generated by script/tailwind.js */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`;
await writeFile(path.join(here, "../src/styles/tailwind/colors.css"), output.trim());
