/** @file Generates and validates prefixed, time-ordered (ascending/descending) identifiers. */
import z from "zod";
const prefixes = {
  session: "ses",
  message: "msg",
  permission: "per",
  user: "usr",
  part: "prt",
  pty: "pty"
};
const LENGTH = 26;
let lastTimestamp = 0;
let counter = 0;
export let Identifier;
(function (_Identifier) {
  /**
   * Build a zod schema that requires a string starting with the given kind's prefix.
   * @param {string} prefix - The identifier kind (e.g. "session", "message").
   * @returns {Object} A zod string schema constrained to the kind's prefix.
   */
  function schema(prefix) {
    return z.string().startsWith(prefixes[prefix]);
  }
  _Identifier.schema = schema;
  /**
   * Generate (or validate a provided) ascending, time-ordered identifier of a kind.
   * @param {string} prefix - The identifier kind.
   * @param {string} given - An optional existing id to validate and return instead.
   * @returns {string} The generated or validated identifier.
   */
  function ascending(prefix, given) {
    return generateID(prefix, false, given);
  }
  _Identifier.ascending = ascending;
  /**
   * Generate (or validate a provided) descending, time-ordered identifier of a kind.
   * @param {string} prefix - The identifier kind.
   * @param {string} given - An optional existing id to validate and return instead.
   * @returns {string} The generated or validated identifier.
   */
  function descending(prefix, given) {
    return generateID(prefix, true, given);
  }
  _Identifier.descending = descending;
})(Identifier || (Identifier = {}));
/**
 * Generate a new identifier, or validate and pass through a provided one.
 * @param {string} prefix - The identifier kind.
 * @param {boolean} descending - When true, produce a descending (reverse-time) id.
 * @param {string} given - An optional existing id; validated to match the prefix.
 * @returns {string} The generated or validated identifier.
 */
function generateID(prefix, descending, given) {
  if (!given) {
    return create(prefix, descending);
  }
  if (!given.startsWith(prefixes[prefix])) {
    throw new Error(`ID ${given} does not start with ${prefixes[prefix]}`);
  }
  return given;
}
/**
 * Build a fresh identifier from a prefix, a time component and random base62 suffix,
 * using a per-timestamp counter to keep ids unique and ordered.
 * @param {string} prefix - The identifier kind.
 * @param {boolean} descending - When true, bit-invert the time component for reverse ordering.
 * @param {number} timestamp - Optional millisecond timestamp; defaults to Date.now().
 * @returns {string} The newly created identifier.
 */
function create(prefix, descending, timestamp) {
  const currentTimestamp = timestamp ?? Date.now();
  if (currentTimestamp !== lastTimestamp) {
    lastTimestamp = currentTimestamp;
    counter = 0;
  }
  counter += 1;
  let now = BigInt(currentTimestamp) * BigInt(0x1000) + BigInt(counter);
  if (descending) {
    now = ~now;
  }
  const timeBytes = new Uint8Array(6);
  for (let i = 0; i < 6; i += 1) {
    timeBytes[i] = Number(now >> BigInt(40 - 8 * i) & BigInt(0xff));
  }
  return prefixes[prefix] + "_" + bytesToHex(timeBytes) + randomBase62(LENGTH - 12);
}
/**
 * Convert a byte array into a zero-padded lowercase hex string.
 * @param {Uint8Array} bytes - The bytes to encode.
 * @returns {string} The hex representation.
 */
function bytesToHex(bytes) {
  let hex = "";
  for (let i = 0; i < bytes.length; i += 1) {
    hex += bytes[i].toString(16).padStart(2, "0");
  }
  return hex;
}
/**
 * Generate a random base62 string of the given length.
 * @param {number} length - The number of characters to produce.
 * @returns {string} A random base62 string.
 */
function randomBase62(length) {
  const chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  const bytes = getRandomBytes(length);
  let result = "";
  for (let i = 0; i < length; i += 1) {
    result += chars[bytes[i] % 62];
  }
  return result;
}
/**
 * Get cryptographically random bytes, falling back to Math.random when crypto is unavailable.
 * @param {number} length - The number of bytes to generate.
 * @returns {Uint8Array} The generated bytes.
 */
function getRandomBytes(length) {
  const bytes = new Uint8Array(length);
  const cryptoObj = typeof globalThis !== "undefined" ? globalThis.crypto : undefined;
  if (cryptoObj && typeof cryptoObj.getRandomValues === "function") {
    cryptoObj.getRandomValues(bytes);
    return bytes;
  }
  for (let i = 0; i < length; i += 1) {
    bytes[i] = Math.floor(Math.random() * 256);
  }
  return bytes;
}